// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package wrp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid0MessageType-0]
	_ = x[Invalid1MessageType-1]
	_ = x[AuthorizationMessageType-2]
	_ = x[SimpleRequestResponseMessageType-3]
	_ = x[SimpleEventMessageType-4]
	_ = x[CreateMessageType-5]
	_ = x[RetrieveMessageType-6]
	_ = x[UpdateMessageType-7]
	_ = x[DeleteMessageType-8]
	_ = x[ServiceRegistrationMessageType-9]
	_ = x[ServiceAliveMessageType-10]
	_ = x[UnknownMessageType-11]
	_ = x[LastMessageType-12]
}

const _MessageType_name = "Invalid0MessageTypeInvalid1MessageTypeAuthorizationMessageTypeSimpleRequestResponseMessageTypeSimpleEventMessageTypeCreateMessageTypeRetrieveMessageTypeUpdateMessageTypeDeleteMessageTypeServiceRegistrationMessageTypeServiceAliveMessageTypeUnknownMessageTypeLastMessageType"

var _MessageType_index = [...]uint16{0, 19, 38, 62, 94, 116, 133, 152, 169, 186, 216, 239, 257, 272}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
