// Code generated by "stringer -type=QOSLevel -linecomment"; DO NOT EDIT.

package wrp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QOSLow-0]
	_ = x[QOSMedium-1]
	_ = x[QOSHigh-2]
	_ = x[QOSCritical-3]
}

const _QOSLevel_name = "LowMediumHighCritical"

var _QOSLevel_index = [...]uint8{0, 3, 9, 13, 21}

func (i QOSLevel) String() string {
	if i < 0 || i >= QOSLevel(len(_QOSLevel_index)-1) {
		return "QOSLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QOSLevel_name[_QOSLevel_index[i]:_QOSLevel_index[i+1]]
}
